# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Mahdi Beitollahi
title: Machine Learning Research Scientist
#email: beitollahi.mahdi
#website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: never

# Social links
#twitter_username: facespics
github_username:  mahdibeit
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
#linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Mahdi and I'm a <mark>machine learning research scientist</mark> with +4 years of experience in industry and academia. I have developed, analyzed, and delivered end-to-end AI products for computer vision, bio-medical sensors, and audio processing to two companies. My research focuses on the implementation of distributed machine learning and privacy-preserving machine learning, and I have three research awards and three publications in this area.


content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left #top-middle
        title: Federated Learning with Autoencoder Compression (FLAC)
        link: github.com/mahdibeit/FLAC
        sub_title: Submitted to IEEE GLOBECOM 2022
        # link_text: Project Website
        additional_links:
          - title:  github.com/mahdibeit/FLAC
            icon: fab fa-github
            url: github.com/mahdibeit/FLAC
            
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        #quote: >
          #This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          In this paper, we propose the Federated Learning with Autoencoder Compression (FLAC) approach that utilizes the redundant information and error-correcting capability of Federated Learning (FL) to compress user devices' models for uplink transmission. FLAC trains an autoencoder to encode and decode users' models at the server in the Training State, and then, sends the autoencoder to user devices for compressing local models for future iterations during the Compression State. We theoretically prove that FLAC converges for FL systems with strongly convex ML models and non-i.i.d. data distribution.
          
          ![alt text](images/FLAC.jpg "FLAC Project")
          
          
      - layout: left #top-middle
        title: Crowd Counting with Perceptual Loss Function
        link: github.com/mahdibeit/FLAC
        #sub_title: Submitted to IEEE GLOBECOM 2022
        # link_text: Project Website
        additional_links:
          - title:  github.com/mahdibeit/Crowd-Counting
            icon: fab fa-github
            url: github.com/mahdibeit/Crowd-Counting
            
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        #quote: >
          #This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          This project aims to develop, analyze, and evaluate methods that can accurately estimate the crowd count from a single image-based and generate the density map of images. To this end, we propose novel ideas in three main parts of preprocessing, model architectures, and loss function of our deep learning pipeline. More specifically, we utilize transfer learning methods by using pre-trained depth and image models to develop depth-guided attention models and VGG-based U-Net architecture to address the limited number of samples in the dataset and increase the accuracy.
         
          ![alt text](images/Crowd.jpg "Crowd Project")
          
          
      - layout: left #top-middle
        title: EEG-Based Brain Computer Interface
        link: https://github.com/mahdibeit/EEG-BasedBCI
        #sub_title: Submitted to IEEE GLOBECOM 2022
        # link_text: Project Website
        additional_links:
          - title:  https://github.com/mahdibeit/EEG-BasedBCI
            icon: fab fa-github
            url: github.com/mahdibeit/Crowd-Counting

          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        #quote: >
          #This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          In this project, we utilized Spatio-temporal Representation Learning for EEG-based Brain-Computer Interfaces. We propose a novel method that can capture spatio-temporal representations of raw EEG in commercial settings using autoencoders. More specifically, we modify the machine learning (ML) pipeline by adding a feature learning preprocessing method that can capture cross-subject informationIn this project, we utilize Pytorch to build an end-to-end classification pipeline for Motor Imagery (MI) tasks using cross-subject data.

          ![alt text](images/BCI.jpg "BCI Project")



  
  - title: Programming Languages and Libraries
    layout: text
    content: | # this will include new lines to allow paragraphs
      Programming languages: <mark>Python</mark>, <mark>C</mark>, <mark>Matlab</mark>, <mark>SQL</mark>, <mark>Java</mark>, <mark>Bash</mark>, <mark>Git</mark>
      
      Libraries: <mark>Python</mark>,  <mark>PyTorch</mark>, <mark>Pandas</mark>, <mark>Tensorflow</mark>, <mark>Flower</mark>, <mark>PySyft</mark>, <mark>Numpy</mark>, <mark>CUDA</mark>, <mark>Sklearn</mark>, <mark>Keras</mark>, <mark>SciPy</mark>, <mark>XGBoost</mark>, <mark>Matplotlib</mark>, <mark>PySpark</mark>, <mark>MLflow</mark>

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
